### ISSUE TITLE
Informative error messages for improper input

### ISSUE THREAD

**Issue by Jacques857** [grapse/PlasMapper_Frontend#6]

**Comment by Jacques857** [comment]
In "enter a sequence" section, if any non atcg characters are found, give a message saying something like "unexpected characters were found and removed. Only ATCG should be input"

**Comment by grapse** [comment]
If sequence is >100k, say "cannot annotate sequences of more than 100k bp"
Soft cap at 100k, hard cap at 500k

**Comment by Jacques857** [comment]
Only allow file extensions ".txt", ".fasta". Include text saying these restrictions nearby the input button
